import type { ApplicationDefinition } from './types'

export const commercialAcord125Definition: ApplicationDefinition = {
  id: 'commercial-acord125',
  lineOfBusiness: 'Commercial Insurance',
  version: 1,
  requirements: [
    {
      id: 'business-legal-name',
      canonicalField: 'business.legalName',
      label: 'Legal name',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
    },
    {
      id: 'business-annual-revenue',
      canonicalField: 'business.annualRevenue',
      label: 'Annual revenue',
      section: 'Business Information',
      inputType: 'currency',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: true,
      validation: { min: 0 },
    },
    {
      id: 'business-naics-code',
      canonicalField: 'business.naicsCode',
      label: 'NAICS code',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
    },
    {
      id: 'business-employee-count',
      canonicalField: 'business.employeeCount',
      label: 'Number of employees',
      section: 'Operations',
      inputType: 'number',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      validation: { min: 1 },
    },
    {
      id: 'business-years-in-business',
      canonicalField: 'business.yearsInBusiness',
      label: 'Years in business',
      section: 'Operations',
      inputType: 'number',
      required: true,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      validation: { min: 0 },
    },
    {
      id: 'business-fein',
      canonicalField: 'business.fein',
      label: 'FEIN',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: true,
    },
    {
      id: 'current-insurance-effective-date',
      canonicalField: 'currentInsurance.effectiveDate',
      label: 'Desired effective date',
      section: 'Coverage',
      inputType: 'date',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
    },
  ],
}

export const commercialGeneralLiabilityDefinition: ApplicationDefinition = {
  id: 'commercial-general-liability',
  lineOfBusiness: 'General Liability',
  version: 1,
  requirements: [
    {
      id: 'gl-legal-name',
      canonicalField: 'business.legalName',
      label: 'Legal business name',
      section: 'Business Info',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
    },
    {
      id: 'gl-annual-revenue',
      canonicalField: 'business.annualRevenue',
      label: 'Gross annual revenue',
      section: 'Business Info',
      inputType: 'currency',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: true,
    },
    {
      id: 'gl-employee-count',
      canonicalField: 'business.employeeCount',
      label: 'Employee count',
      section: 'Operations',
      inputType: 'number',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
    },
    {
      id: 'gl-fein',
      canonicalField: 'business.fein',
      label: 'FEIN',
      section: 'Business Info',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: true,
    },
  ],
}

export const commercialAutoDefinition: ApplicationDefinition = {
  id: 'commercial-auto',
  lineOfBusiness: 'Commercial Auto',
  version: 1,
  requirements: [
    {
      id: 'auto-legal-name',
      canonicalField: 'business.legalName',
      label: 'Named insured',
      section: 'Business Info',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
    },
    {
      id: 'auto-fein',
      canonicalField: 'business.fein',
      label: 'FEIN',
      section: 'Business Info',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: true,
    },
    {
      id: 'auto-vehicle-year',
      canonicalField: 'vehicle.year',
      label: 'Vehicle year',
      section: 'Schedule of Vehicles',
      inputType: 'number',
      required: true,
      material: false,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
    },
    {
      id: 'auto-vehicle-make',
      canonicalField: 'vehicle.make',
      label: 'Vehicle make',
      section: 'Schedule of Vehicles',
      inputType: 'text',
      required: true,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
    },
  ],
}

export const commercialAcord125DefinitionV2: ApplicationDefinition = {
  id: 'commercial-acord125',
  lineOfBusiness: 'Commercial Insurance',
  version: 2,
  requirements: [
    {
      id: 'business-legal-name',
      canonicalField: 'business.legalName',
      label: 'Legal name',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 1,
      questionOrder: 1,
      helperText: 'Official registered legal name of the business entity.',
      profileReusable: true,
    },
    {
      id: 'business-annual-revenue',
      canonicalField: 'business.annualRevenue',
      label: 'Annual revenue',
      section: 'Business Information',
      inputType: 'currency',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: true,
      validation: { min: 0 },
      sectionOrder: 1,
      questionOrder: 2,
      helperText: 'Gross annual revenue for the most recent 12 months.',
      profileReusable: true,
    },
    {
      id: 'business-naics-code',
      canonicalField: 'business.naicsCode',
      label: 'NAICS code',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      sectionOrder: 1,
      questionOrder: 3,
      helperText: 'Primary 6-digit NAICS industry classification code.',
      profileReusable: true,
    },
    {
      id: 'business-fein',
      canonicalField: 'business.fein',
      label: 'FEIN',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: true,
      sectionOrder: 1,
      questionOrder: 4,
      helperText: '9-digit Federal Employer Identification Number (XX-XXXXXXX).',
      profileReusable: true,
    },
    {
      id: 'business-employee-count',
      canonicalField: 'business.employeeCount',
      label: 'Number of employees',
      section: 'Operations',
      inputType: 'number',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      validation: { min: 1 },
      sectionOrder: 2,
      questionOrder: 1,
      helperText: 'Total full-time and part-time employee headcount.',
      profileReusable: true,
    },
    {
      id: 'business-years-in-business',
      canonicalField: 'business.yearsInBusiness',
      label: 'Years in business',
      section: 'Operations',
      inputType: 'number',
      required: true,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      validation: { min: 0 },
      sectionOrder: 2,
      questionOrder: 2,
      helperText: 'Number of years the business has been operating.',
      profileReusable: true,
    },
    {
      id: 'app-desired-effective-date',
      canonicalField: 'application.desiredEffectiveDate',
      label: 'Desired effective date',
      section: 'Coverage',
      inputType: 'date',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 3,
      questionOrder: 1,
      helperText: 'Date when coverage for this specific application should begin.',
      profileReusable: false,
    },
  ],
}

export const commercialGeneralLiabilityDefinitionV2: ApplicationDefinition = {
  id: 'commercial-general-liability',
  lineOfBusiness: 'General Liability',
  version: 2,
  requirements: [
    // Section 1: Business Information
    {
      id: 'gl-legal-name',
      canonicalField: 'business.legalName',
      label: 'Legal business name',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 1,
      questionOrder: 1,
      helperText: 'Official legal name as registered with the secretary of state.',
      profileReusable: true,
    },
    {
      id: 'gl-dba',
      canonicalField: 'business.dba',
      label: 'DBA / Trade name',
      section: 'Business Information',
      inputType: 'text',
      required: false,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      sectionOrder: 1,
      questionOrder: 2,
      helperText: 'Doing Business As or trade name if different from legal name.',
      profileReusable: true,
    },
    {
      id: 'gl-entity-type',
      canonicalField: 'business.entityType',
      label: 'Entity type',
      section: 'Business Information',
      inputType: 'select',
      options: [
        { label: 'Limited Liability Company (LLC)', value: 'LLC' },
        { label: 'Corporation (C-Corp / S-Corp)', value: 'Corporation' },
        { label: 'Partnership', value: 'Partnership' },
        { label: 'Sole Proprietorship', value: 'Sole Proprietorship' },
      ],
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 1,
      questionOrder: 3,
      helperText: 'Legal structure under which the business is organized.',
      profileReusable: true,
    },
    {
      id: 'gl-fein',
      canonicalField: 'business.fein',
      label: 'Federal Tax ID (FEIN)',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: true,
      sectionOrder: 1,
      questionOrder: 4,
      helperText: '9-digit Federal Employer Identification Number.',
      profileReusable: true,
    },
    {
      id: 'gl-state-formation',
      canonicalField: 'business.stateOfFormation',
      label: 'State of formation',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      sectionOrder: 1,
      questionOrder: 5,
      helperText: 'US State where the business entity was incorporated or organized.',
      profileReusable: true,
    },
    {
      id: 'gl-years-in-business',
      canonicalField: 'business.yearsInBusiness',
      label: 'Years in business',
      section: 'Business Information',
      inputType: 'number',
      required: true,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      validation: { min: 0 },
      sectionOrder: 1,
      questionOrder: 6,
      helperText: 'Total number of years under current ownership.',
      profileReusable: true,
    },
    {
      id: 'gl-naics-code',
      canonicalField: 'business.naicsCode',
      label: 'NAICS code',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      sectionOrder: 1,
      questionOrder: 7,
      helperText: '6-digit NAICS classification code representing primary operations.',
      profileReusable: true,
    },
    {
      id: 'gl-annual-revenue',
      canonicalField: 'business.annualRevenue',
      label: 'Gross annual revenue',
      section: 'Business Information',
      inputType: 'currency',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: true,
      validation: { min: 0 },
      sectionOrder: 1,
      questionOrder: 8,
      helperText: 'Projected gross revenue for the upcoming 12-month policy period.',
      profileReusable: true,
    },
    {
      id: 'gl-employee-count',
      canonicalField: 'business.employeeCount',
      label: 'Employee headcount',
      section: 'Business Information',
      inputType: 'number',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      validation: { min: 1 },
      sectionOrder: 1,
      questionOrder: 9,
      helperText: 'Total number of active full-time and part-time staff.',
      profileReusable: true,
    },
    {
      id: 'gl-business-description',
      canonicalField: 'business.description',
      label: 'Business summary',
      section: 'Business Information',
      inputType: 'text',
      required: true,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      sectionOrder: 1,
      questionOrder: 10,
      helperText: 'Detailed description of the daily operations and business activities.',
      profileReusable: true,
    },

    // Section 2: Contact & Location
    {
      id: 'gl-primary-contact',
      canonicalField: 'person.fullName',
      label: 'Primary contact name',
      section: 'Contact & Location',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 2,
      questionOrder: 1,
      helperText: 'Name of the designated authorized business representative.',
      profileReusable: true,
    },
    {
      id: 'gl-primary-location',
      canonicalField: 'location.addressLine1',
      label: 'Primary operating address',
      section: 'Contact & Location',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 2,
      questionOrder: 2,
      helperText: 'Physical street address of the primary business premises.',
      profileReusable: true,
    },

    // Section 3: Current Insurance & Desired Effective Date
    {
      id: 'gl-prior-carrier',
      canonicalField: 'currentInsurance.carrierName',
      label: 'Current insurance carrier',
      section: 'Current Insurance',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 3,
      questionOrder: 1,
      helperText: 'Name of the current general liability or package insurance carrier.',
      profileReusable: true,
    },
    {
      id: 'gl-prior-expiration',
      canonicalField: 'currentInsurance.expirationDate',
      label: 'Policy expiration date',
      section: 'Current Insurance',
      inputType: 'date',
      required: true,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      sectionOrder: 3,
      questionOrder: 2,
      helperText: 'Expiration date of the current active insurance policy.',
      profileReusable: true,
    },
    {
      id: 'gl-current-limits',
      canonicalField: 'currentInsurance.limits',
      label: 'Current policy limits',
      section: 'Current Insurance',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 3,
      questionOrder: 3,
      helperText: 'Current general liability occurrence / aggregate limits (e.g., $1,000,000 / $2,000,000).',
      profileReusable: true,
    },
    {
      id: 'gl-current-premium',
      canonicalField: 'currentInsurance.premium',
      label: 'Expiring annual premium',
      section: 'Current Insurance',
      inputType: 'currency',
      required: false,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      sectionOrder: 3,
      questionOrder: 4,
      helperText: 'Annual premium paid on expiring policy.',
      profileReusable: true,
    },
    {
      id: 'gl-desired-effective-date',
      canonicalField: 'application.desiredEffectiveDate',
      label: 'Desired effective date',
      section: 'Current Insurance',
      inputType: 'date',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 3,
      questionOrder: 5,
      helperText: 'Requested inception date for the new policy period.',
      profileReusable: false,
    },

    // Section 4: Loss History
    {
      id: 'gl-loss-history',
      canonicalField: 'loss.description',
      label: 'Prior loss history / claims',
      section: 'Loss History',
      inputType: 'text',
      required: true,
      material: false,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 4,
      questionOrder: 1,
      helperText: 'Summary of any general liability claims or incidents in the past 3-5 years (or "No losses").',
      profileReusable: true,
    },

    // Section 5: General Liability Exposures
    {
      id: 'gl-subcontractor-usage',
      canonicalField: 'gl.subcontractorUsage',
      label: 'Do you hire independent subcontractors?',
      section: 'General Liability Exposures',
      inputType: 'boolean',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 5,
      questionOrder: 1,
      helperText: 'Indicate whether any operational work is performed by third-party subcontractors.',
      profileReusable: true,
    },
    {
      id: 'gl-subcontractor-percent',
      canonicalField: 'gl.subcontractorPercent',
      label: 'Subcontracted work percentage',
      section: 'General Liability Exposures',
      inputType: 'number',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      validation: { min: 0, max: 100 },
      applicability: {
        field: 'gl.subcontractorUsage',
        equals: true,
      },
      sectionOrder: 5,
      questionOrder: 2,
      helperText: 'Percentage of total operational revenue/cost paid to subcontractors (0-100%).',
      profileReusable: true,
    },
    {
      id: 'gl-work-mix',
      canonicalField: 'gl.residentialCommercialMix',
      label: 'Residential vs. commercial mix',
      section: 'General Liability Exposures',
      inputType: 'text',
      required: true,
      material: true,
      requiresCustomerConfirmation: true,
      requiresBrokerVerification: false,
      sectionOrder: 5,
      questionOrder: 3,
      helperText: 'Breakdown of operations (e.g., 70% Commercial, 30% Residential).',
      profileReusable: true,
    },
    {
      id: 'gl-operations-desc',
      canonicalField: 'gl.operationsDescription',
      label: 'Detailed liability operations description',
      section: 'General Liability Exposures',
      inputType: 'text',
      required: true,
      material: false,
      requiresCustomerConfirmation: false,
      requiresBrokerVerification: false,
      sectionOrder: 5,
      questionOrder: 4,
      helperText: 'Specific hazards, job site conditions, or special equipment used in daily operations.',
      profileReusable: true,
    },
  ],
}

const definitions = [
  commercialAcord125Definition,
  commercialAcord125DefinitionV2,
  commercialGeneralLiabilityDefinition,
  commercialGeneralLiabilityDefinitionV2,
  commercialAutoDefinition,
]

export const getAvailableDefinitions = () => definitions

export const getApplicationDefinition = (definitionId: string, version: number) => {
  const definition = definitions.find((candidate) => candidate.id === definitionId && candidate.version === version)
  if (!definition) {
    throw new Error(`Unknown application definition: ${definitionId}@${version}`)
  }

  return definition
}
